version: '3.0'

services:
  app:
    image: ${DOCKER_REGISTRY}/ros-humble-rust/base:v1.4
    environment:
      CMAKE_PREFIX_PATH: "/opt/ros/humble"
      CI_BOT_ARTIFACTORY_PASSWORD: ${CI_BOT_ARTIFACTORY_PASSWORD}
      CI_BOT_USERNAME: ${CI_BOT_USERNAME}
    volumes:
      - ..:/app
      - ~/.zshrc:/root/.zshrc
      - ~/.oh-my-zsh/custom:/root/.oh-my-zsh/custom
      - ~/.p10k.zsh:/root/.p10k.zsh
    command: tail -f
