build:
	docker build -t vnc-ubuntu-local:focal .

build-ros1:
	docker build -f Dockerfile.ros1 -t vnc-ros1-ubuntu-local:focal .

build-ros2:
	docker build -f Dockerfile.ros2 -t vnc-ros2-ubuntu-local:focal .
